name: Lint

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    name: PSR-12

    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: phpcs
      - run: phpcs --extensions=php --standard=PSR12 --colors -n .
